function LOV(paramConfig)
{var configuracion={nombre:'',url:'',title:'',datos:[],pageSize:10};var value='';var value_id=undefined;var contenedor_id;var contenedor_value;var valores_seleccionados=new Array();if(paramConfig.nombre!==null){configuracion.nombre=paramConfig.nombre;}
if(paramConfig.url!==null){configuracion.url=paramConfig.url;}
if(paramConfig.title!==null){configuracion.title=paramConfig.title;}
if(paramConfig.datos!==null){configuracion.datos=paramConfig.datos;}
if(paramConfig.filterCols!==null){configuracion.filterCols=paramConfig.filterCols;}
if(paramConfig.filterValues!==null){configuracion.filterValues=paramConfig.filterValues;}
if(paramConfig.pageSize!==null){configuracion.pageSize=paramConfig.pageSize;}
var paramLOV={modal:true,autoTabs:false,width:450,height:300,shadow:false,minWidth:150,minHeight:200,fixedCenter:true,constraIntoviewport:true,draggable:true,proxyDrag:true,closable:true,center_split:false,center_titlebar:false,center_autoscroll:true,south_split:false,south_titlebar:false};var smLOV;var cmLOV;var dsLOV;var dom_dlgLOV;var dom_gridLOV;var dlgLOV=false;var gridLOV;var layoutLOV;this.iniciaLOV=function(){var atiqueta_html="<div id='dlgLOV_"+configuracion.nombre+"'><div class='x-dlg-hd'>"+configuracion.title+"</div><div id='gridLOV_"+configuracion.nombre+"'></div></div>";Ext.DomHelper.insertHtml('afterBegin',document.body,atiqueta_html);dom_dlgLOV=Ext.get('dlgLOV_'+configuracion.nombre);dom_gridLOV=Ext.get('gridLOV_'+configuracion.nombre);var showBtn;if(!dlgLOV){dlgLOV=new Ext.LayoutDialog(dom_dlgLOV,{modal:paramLOV.modal,autoTabs:paramLOV.autoTabs,width:paramLOV.width,height:paramLOV.height,shadow:paramLOV.shadow,minWidth:paramLOV.minWidth,minHeight:paramLOV.minHeight,fixedCenter:paramLOV.fixedCenter,constraIntoviewport:paramLOV.constraIntoviewport,draggable:paramLOV.draggable,proxyDrag:paramLOV.proxyDrag,closable:paramLOV.closable,center:{split:paramLOV.center_split,titlebar:paramLOV.center_titlebar,autoScroll:paramLOV.center_autoscroll}});dlgLOV.addKeyListener(27,ocultarLOV);dlgLOV.addButton('Seleccionar',Seleccionar);dlgLOV.addButton('Cancelar',ocultarLOV);dlgLOV.on('beforehide',function(tab,e){var ColFiltro=configuracion.datos[0].dataIndex;if(configuracion.datos[0].filterColValue!==undefined){ColFiltro=configuracion.datos[0].filterColValue;}
dsLOV.lastOptions={params:{start:0,limit:configuracion.pageSize,CantFiltros:'1',filterCol_0:ColFiltro,filterValue_0:''}};ActualizaVariablesFiltro();return true;});layoutLOV=dlgLOV.getLayout();layoutLOV.beginUpdate();layoutLOV.add('center',new Ext.ContentPanel(dom_gridLOV,{fitToFrame:true,closable:false,title:configuracion.title}));layoutLOV.endUpdate();}
var xml=new Array();for(var i=0;i<configuracion.datos.length;i++){xml[i]=configuracion.datos[i].dataIndex;}
dsLOV=new Ext.data.Store({proxy:new Ext.data.HttpProxy({url:configuracion.url}),reader:new Ext.data.XmlReader({record:'ROWS',id:xml[0],totalRecords:'TotalCount'},xml),remoteSort:true});dsLOV.lastOptions={params:{start:0,limit:configuracion.pageSize,CantFiltros:1,filterCol_0:xml[0],filterValue_0:''}};ActualizaVariablesFiltro();dsLOV.addListener('loadexception',conexionFailure);var datos_column=new Array;for(i=1;i<configuracion.datos.length;i++){datos_column[i-1]=configuracion.datos[i];}
cmLOV=new Ext.grid.DefaultColumnModel(datos_column);cmLOV.defaultSortable=true;smLOV=new Ext.grid.RowSelectionModel({singleSelect:true});smLOV.addListener('rowselect',EnableSelectLOV);gridLOV=new Ext.grid.EditorGrid(dom_gridLOV,{ds:dsLOV,cm:cmLOV,selModel:smLOV,enableColLock:false});gridLOV.render();function onResize(){var gridView=gridLOV.getView();gridView.layout();}
layoutLOV.addListener('layout',onResize);var gridFootLOV=gridLOV.getView().getFooterPanel(true);var pagingLOV=new Ext.PagingToolbar(gridFootLOV,dsLOV,{pageSize:configuracion.pageSize,displayInfo:false,displayMsg:'registros {0} - {1} de {2}',emptyMsg:"No hay registros para mostrar"});InitFiltro(pagingLOV);};var iniciaLOV=this.iniciaLOV;function InitFiltro(Barra)
{Barra.addSeparator();var quickMenuItems=new Array('<b class="menu-title">Filtrar Por</b>');var atributosLov=configuracion.datos.length;for(var j=1;j<atributosLov;j++)
{value=configuracion.datos[j].dataIndex;if(configuracion.datos[j].filterColValue!==undefined){value=configuracion.datos[j].filterColValue;}
text=configuracion.datos[j].header;if(j==1){quickMenuItems.push(new Ext.menu.CheckItem({value:value,text:text,checked:true}));}
else{quickMenuItems.push(new Ext.menu.CheckItem({value:value,text:text,checked:false}));}}
var quickMenu=new Ext.menu.Menu({id:'quickMenu_'+configuracion.nombre,items:quickMenuItems});Barra.add({text:'Filtro',tooltip:'Columnas por las que se filtra',icon:'../../../lib/images/m.png',cls:'x-btn-text-icon btn-search-icon',menu:quickMenu});var sftb=Barra.addDom({tag:'input',id:'quicksearch_'+configuracion.nombre,type:'text',size:30,value:'',style:'background: #F0F0F9;'});var searchBox=new Ext.form.Field({emptyText:"Type to quicksearch"});searchBox.applyTo('quicksearch_'+configuracion.nombre);var onFilteringBeforeQuery=function(e){var sw=true;var filterCol="";var cuentaCol=0;for(var p=0,items=quickMenuItems,len=items.length;p<len;p++)
{if(items[p].checked)
{cuentaCol++;if(sw)
{filterCol=items[p].value;sw=false;}
else
{filterCol=filterCol+"#"+items[p].value;}}}
if(cuentaCol===0){searchBox.setValue("");searchBox.disable();}
else{searchBox.enable();}
var value=searchBox.getValue();dsLOV.lastOptions.params["filterCol_0"]=filterCol;dsLOV.lastOptions.params.start=0;dsLOV.lastOptions.params["filterValue_0"]=value;dsLOV.load(dsLOV.lastOptions);};quickMenu.on('click',onFilteringBeforeQuery);searchBox.el.on('keyup',onFilteringBeforeQuery,searchBox);}
this.ocultarLOV=function(){dlgLOV.hide();};var ocultarLOV=this.ocultarLOV;this.loadLOV=function(ds){ds.load(ds.lastOptions);};var loadLOV=this.loadLOV;this.EnableSelectLOV=function(selModel,row,selected){var SelectionsRecordLOV=selModel.getSelected();if(selected&&SelectionsRecordLOV!=-1){value_id=SelectionsRecordLOV.data[configuracion.datos[0].dataIndex];value=SelectionsRecordLOV.data[configuracion.datos[1].dataIndex];for(var q=0;q<configuracion.datos.length;q++){valores_seleccionados[configuracion.datos[q].dataIndex]=SelectionsRecordLOV.data[configuracion.datos[q].dataIndex];}}};var EnableSelectLOV=this.EnableSelectLOV;this.Seleccionar=function(){var NumSelect=smLOV.getCount();if(NumSelect!=0){if(paramConfig.origen=='formulario'){contenedor_value.setValue(value);paramConfig.contenedor_id.setValue(value_id);}
else{var SelectionsRecord=paramConfig.sm.getSelected();contenedor_value.setValue(value);SelectionsRecord.set(paramConfig.contenedor_id,value_id);SelectionsRecord.set(paramConfig.name,value);}
ocultarLOV();}
else{Ext.MessageBox.alert('Status','Seleccione un item primero.');}};var Seleccionar=this.Seleccionar;iniciaLOV();this.smLOV=smLOV;this.cmLOV=cmLOV;this.dsLOV=dsLOV;this.dlgLOV=dlgLOV;this.gridLOV=gridLOV;this.mostrarLOV=function(cajaValue){contenedor_value=cajaValue;ActualizaVariablesFiltro();this.dsLOV.load(this.dsLOV.lastOptions);this.smLOV.clearSelections();this.dlgLOV.show();};var mostrarLOV=this.mostrarLOV;function ActualizaVariablesFiltro(){for(var k=0;k<configuracion.filterValues.length;k++){var indice=k+1;dsLOV.lastOptions.params["filterCol_"+indice]=configuracion.filterCols[k];dsLOV.lastOptions.params["filterValue_"+indice]=configuracion.filterValues[k];dsLOV.lastOptions.params["filterAvanzado_"+indice]=true;}
dsLOV.lastOptions.params.CantFiltros=configuracion.filterValues.length+1;}
this.modifica_filterCols=function(indice,valor){configuracion.filterCols[indice]=valor;};var modifica_filterCols=this.modifica_filterCols;this.modifica_filterValues=function(indice,valor){configuracion.filterValues[indice]=valor;};varmodifica_filterValues=this.modifica_filterValues;this.recuperar_valoresSelecionados=function(){return valores_seleccionados;}
recuperar_valoresSelecionados=this.recuperar_valoresSelecionados;function conexionFailure(resp1,resp2,resp3){resp=resp3;var sw=false;if(resp.status==404&&!sw){var mensaje="<p>HTTP status: "+resp.status+" <br/> Status: "+resp.statusText+"<br/> No se encontro el Action requerido</p>";Ext.Msg.show({title:'ERROR',msg:mensaje,minWidth:300,maxWidth:800,buttons:Ext.Msg.OK});sw=true;}
if(resp.responseXML!=undefined&&resp.responseXML!=null&&!sw&&resp.responseXML.documentElement!=null&&resp.responseXML.documentElement!=undefined){var root=resp.responseXML.documentElement;if(root.getElementsByTagName('mensaje')[0]){var oMensaje=root.getElementsByTagName('mensaje')[0].firstChild.nodeValue;var mensaje="HTTP status: "+resp.status+"<br/> Status: "+resp.statusText+"<br>"+oMensaje;}
else{var mensaje="HTTP status: "+resp.status+"<br/> Status: "+resp.statusText+"<br>"+resp.responseText;}
Ext.Msg.show({title:'ERROR',msg:mensaje,minWidth:300,maxWidth:800,buttons:Ext.Msg.OK});sw=true;}
else{if(resp.status===-1&&!sw){var mensaje="<p>HTTP status: "+resp.status+"<br/> Status: "+resp.statusText+"<br/> Tiempo de espera agotado</p>";Ext.Msg.show({title:'ERROR',msg:mensaje,minWidth:300,maxWidth:800,buttons:Ext.Msg.OK});sw=true;}
if(resp.status===0&&!sw){var mensaje="HTTP status: "+resp.status+"<br/> Status: "+resp.statusText+"<br/> Fallo en su conexión de Internet";Ext.Msg.show({title:'ERROR',msg:mensaje,minWidth:300,maxWidth:800,buttons:Ext.Msg.OK});sw=true;}
if(!sw){var mensaje="respuesta indefinida, error en la transmision <br> respuesta obtenida:<br>"+resp.responseText;Ext.Msg.show({title:'ERROR',msg:mensaje,minWidth:300,maxWidth:800,buttons:Ext.Msg.OK});}}}
this.conexionFailure=conexionFailure;}
Ext.form.LovTriggerField=function(config){Ext.form.LovTriggerField.superclass.constructor.call(this,config);this.nombre=this.getId();configuracion={nombre:this.nombre,url:this.url,title:this.title,datos:this.datos,filterCols:this.filterCols,filterValues:this.filterValues,pageSize:this.pageSize,contenedor_id:this.contenedor_id,origen:this.origen,sm:this.sm,name:this.name};this.lov=new LOV(configuracion);};Ext.extend(Ext.form.LovTriggerField,Ext.form.TriggerField,{defaultAutoCreate:{tag:"input",type:"text",size:"24",autocomplete:"off"},nombre:undefined,url:'',title:'',datos:[],filterCols:[],filterValues:[],pageSize:10,paramLOV:{modal:false,autoTabs:false,width:450,height:300,shadow:false,minWidth:150,minHeight:200,fixedCenter:true,constraIntoviewport:true,draggable:true,proxyDrag:true,closable:true,center_split:false,center_titlebar:false,center_autoscroll:true,south_split:false,south_titlebar:false},smLOV:undefined,cmLOV:undefined,dsLOV:undefined,dom_dlgLOV:undefined,dom_gridLOV:undefined,dlgLOV:false,gridLOV:undefined,layoutLOV:undefined,pagingLOV:undefined,triggerClass:'x-form-search-trigger',value:undefined,value_id:undefined,editable:false,onTriggerClick:function(){this.lov.mostrarLOV(this);},initEvents:function(){Ext.form.ComboBox.superclass.initEvents.call(this);this.keyNav=new Ext.KeyNav(this.el,{"enter":function(e){this.lov.mostrarLOV(this);},"esc":function(e){this.lov.ocultarLOV();}});this.el.dom.setAttribute('readOnly',true);this.el.addClass('x-combo-noedit');}});